const express = require('express')
const monito_JD = require('../controller/monito/monito_JD')
const monito_TM = require('../controller/monito/monito_TM')
const check = require('../middlewares/check')
const router = express.Router()
router.get('/jd/addgoods', check.checkUser, monito_JD.addgoods)
router.delete('/jd/delgoods', check.checkUser, monito_JD.delgoods)
router.get('/jd/getgoods', check.checkUser, monito_JD.getGoods)
router.get('/tm/addgoods', check.checkUser, monito_TM.addGoods)
router.delete('/tm/delgoods', check.checkUser, monito_TM.delGoods)
router.get('/tm/getgoods', check.checkUser, monito_TM.getGoods)
module.exports = router