const express = require('express')
const monito_JD = require('../controller/monito/monito_JD')
const monito_TM = require('../controller/monito/monito_TM')
const check = require('../middlewares/check')
const router = express.Router()
router.get('/jd/addgoods', check.checkuser, monito_JD.addgoods)
router.delete('/jd/delgoods', check.checkuser, monito_JD.delgoods)
router.get('/jd/getgoods', check.checkuser, monito_JD.getgoods)
router.get('/tm/addgoods', check.checkuser, monito_TM.addgoods)
router.delete('/tm/delgoods', check.checkuser, monito_TM.delgoods)
router.get('/tm/getgoods', check.checkuser, monito_TM.getgoods)
module.exports = router